[application]
name = "signal-noise"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "The AIrony Times"
base_path = "/"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []

[server]
port = 8888
ip = "0.0.0.0"
