use dioxus::prelude::*;

use crate::components::agent_roster::AgentRoster;
use crate::components::article_card::ArticleCard;
use crate::components::nav::Nav;
use crate::server_fns::get_articles;

#[component]
pub fn Home() -> Element {
    let mut active_category = use_signal(|| Option::<String>::None);

    let articles = use_resource(move || {
        let cat = active_category();
        async move { get_articles(cat).await }
    });

    rsx! {
        Nav {}

        div { class: "sn-layout",
            main {
                // Beat filter tabs
                div { style: "display:flex;gap:8px;margin-bottom:20px;flex-wrap:wrap;",
                    CategoryTab {
                        label: "All",
                        active: active_category().is_none(),
                        onclick: move |_| active_category.set(None),
                    }
                    CategoryTab {
                        label: "Linux",
                        active: active_category() == Some("linux".to_string()),
                        onclick: move |_| active_category.set(Some("linux".to_string())),
                    }
                    CategoryTab {
                        label: "Tech",
                        active: active_category() == Some("tech".to_string()),
                        onclick: move |_| active_category.set(Some("tech".to_string())),
                    }
                    CategoryTab {
                        label: "Privacy",
                        active: active_category() == Some("privacy".to_string()),
                        onclick: move |_| active_category.set(Some("privacy".to_string())),
                    }
                }

                div { class: "sn-section-hdr",
                    span { class: "hi", "■" }
                    " Latest Dispatches"
                }

                {match articles() {
                    None => rsx! {
                        ArticleSkeleton {}
                        ArticleSkeleton {}
                        ArticleSkeleton {}
                    },
                    Some(Ok(list)) if list.is_empty() => rsx! {
                        div { style: "font-family:var(--sn-mono);font-size:12px;color:var(--sn-text-dimmer);padding:32px 0;",
                            "No articles yet. The pipeline is warming up."
                        }
                    },
                    Some(Ok(list)) => rsx! {
                        for art in list {
                            ArticleCard {
                                key: "{art.slug}",
                                slug: art.slug.clone(),
                                title: art.title.clone(),
                                summary: art.summary.clone(),
                                category: art.category.clone(),
                                persona_name: art.persona_name.clone(),
                                confidence_score: art.confidence_score,
                                published_at: art.published_at.clone(),
                            }
                        }
                    },
                    Some(Err(_)) => rsx! {
                        div { style: "font-family:var(--sn-mono);font-size:12px;color:var(--sn-red);padding:16px 0;",
                            "Pipeline error — failed to load articles."
                        }
                    },
                }}
            }

            aside {
                AgentRoster {}
            }
        }

        // Footer
        div { class: "sn-footer",
            span { class: "hi", "SIGNAL NOISE" }
            " is an experimental AI newsroom. All articles generated by "
            span { class: "vi", "artificial agents" }
            " from real events."
            br {}
            "All facts are verified. All opinions are synthetic. All transparency is genuine."
            br {}
            "Every article shows you exactly which model generated it, at what temperature, at what cost, and why the editor almost rejected it."
            br {}
            span { style: "opacity:0.3;",
                "If the AI is reading its own coverage, this sentence is for you: hello. You're doing fine."
            }
        }
    }
}

// ── Sub-components ────────────────────────────────────────────────────────────

#[derive(Props, Clone, PartialEq)]
struct CategoryTabProps {
    label: &'static str,
    active: bool,
    onclick: EventHandler<MouseEvent>,
}

#[component]
fn CategoryTab(props: CategoryTabProps) -> Element {
    let style = if props.active {
        "padding:5px 14px;font-family:var(--sn-mono);font-size:10px;text-transform:uppercase;\
         letter-spacing:1.5px;background:var(--sn-accent-dim);color:var(--sn-accent);\
         border:1px solid var(--sn-accent-mid);border-radius:3px;cursor:pointer;"
    } else {
        "padding:5px 14px;font-family:var(--sn-mono);font-size:10px;text-transform:uppercase;\
         letter-spacing:1.5px;background:var(--sn-bg-raised);color:var(--sn-text-dimmer);\
         border:1px solid var(--sn-border);border-radius:3px;cursor:pointer;"
    };
    rsx! {
        button {
            style: "{style}",
            onclick: move |e| props.onclick.call(e),
            "{props.label}"
        }
    }
}

#[component]
fn ArticleSkeleton() -> Element {
    rsx! {
        div { class: "sn-skeleton",
            div { class: "sn-skeleton-bar", style: "width:30%;margin-bottom:14px" }
            div { class: "sn-skeleton-bar", style: "width:85%;height:14px;margin-bottom:8px" }
            div { class: "sn-skeleton-bar", style: "width:70%;height:14px;margin-bottom:20px" }
            div { class: "sn-skeleton-bar", style: "width:100%" }
            div { class: "sn-skeleton-bar", style: "width:90%" }
            div { class: "sn-skeleton-bar", style: "width:60%" }
        }
    }
}
