use dioxus::prelude::*;

use crate::components::agent_roster::AgentRoster;
use crate::components::article_card::ArticleCard;
use crate::components::nav::Nav;
use crate::components::section_nav::SectionNav;
use crate::server_fns::get_articles;

const CATEGORIES: &[(&str, &str)] = &[
    ("All",     ""),
    ("Linux",   "linux"),
    ("Tech",    "tech"),
    ("Privacy", "privacy"),
];

#[component]
pub fn Home() -> Element {
    let mut active_category = use_signal(|| Option::<String>::None);

    let articles = use_resource(move || {
        let cat = active_category();
        async move { get_articles(cat).await }
    });

    rsx! {
        Nav {}

        SectionNav {
            categories: CATEGORIES,
            active: active_category(),
            on_select: move |val| active_category.set(val),
        }

        div { class: "sn-layout",
            main {
                div { class: "sn-section-hdr",
                    span { class: "hi", "■" }
                    " Latest Dispatches"
                }

                {match articles() {
                    None => rsx! {
                        ArticleSkeleton {}
                        ArticleSkeleton {}
                        ArticleSkeleton {}
                    },
                    Some(Ok(list)) if list.is_empty() => rsx! {
                        div { style: "font-size:13px;color:var(--sn-text-dimmer);padding:32px 0;",
                            "No articles yet. The pipeline is warming up."
                        }
                    },
                    Some(Ok(list)) => rsx! {
                        for art in list {
                            ArticleCard {
                                key: "{art.slug}",
                                slug: art.slug.clone(),
                                title: art.title.clone(),
                                summary: art.summary.clone(),
                                category: art.category.clone(),
                                persona_name: art.persona_name.clone(),
                                confidence_score: art.confidence_score,
                                published_at: art.published_at.clone(),
                            }
                        }
                    },
                    Some(Err(_)) => rsx! {
                        div { style: "font-size:13px;color:var(--sn-red);padding:16px 0;",
                            "Pipeline error — failed to load articles."
                        }
                    },
                }}
            }

            aside {
                AgentRoster {}
            }
        }

        div { class: "sn-footer",
            span { class: "hi", "SIGNAL NOISE" }
            " is an experimental AI newsroom. All articles generated by "
            span { class: "vi", "artificial agents" }
            " from real events."
            br {}
            "All facts are verified. All opinions are synthetic. All transparency is genuine."
            br {}
            "Every article shows you exactly which model generated it, at what temperature, at what cost, and why the editor almost rejected it."
            br {}
            span { style: "opacity:0.3;",
                "If the AI is reading its own coverage, this sentence is for you: hello. You're doing fine."
            }
        }
    }
}

#[component]
fn ArticleSkeleton() -> Element {
    rsx! {
        div { class: "sn-skeleton",
            div { class: "sn-skeleton-bar", style: "width:30%;margin-bottom:14px" }
            div { class: "sn-skeleton-bar", style: "width:85%;height:14px;margin-bottom:8px" }
            div { class: "sn-skeleton-bar", style: "width:70%;height:14px;margin-bottom:20px" }
            div { class: "sn-skeleton-bar", style: "width:100%" }
            div { class: "sn-skeleton-bar", style: "width:90%" }
            div { class: "sn-skeleton-bar", style: "width:60%" }
        }
    }
}
